# Default values for kraken.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

default:
  - &default_tag 3.0.0-rc1
  - &default_admin_pwd kraken


rbac:
  create: true

ingress:
  enabled: true
  annotations: {}
#    kubernetes.io/ingress.global-static-ip-name: web-static-ip

keycloak:
  image:
    repository: octoperf/kraken-keycloak
    tag: *default_tag
  username: admin
  password: *default_admin_pwd
  ingress:
    enabled: true
  persistence:
    deployPostgres: true
  extraEnv: |
    - name: KEYCLOAK_WELCOME_THEME
      value: "kraken"
    - name: KRAKEN_SECURITY_URL
      value: "http://kraken.local:9080"
    - name: KRAKEN_URLS
      value: "http://kraken.local:8080/user-events,http://kraken.local:8081/user-events"
    - name: KRAKEN_SECURITY_API_ID
      value: "kraken-api"
    - name: KRAKEN_SECURITY_API_SECRET
      value: "c1ab32c0-0ba7-4289-b6c9-0ea1aa5ad1d4"
    - name: KRAKEN_SECURITY_REALM
      value: "kraken"
  # TODO
  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret
  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/realm/"
      readOnly: true
  extraArgs: -Dkeycloak.import=/realm/realm.json

grafana:
  fullnameOverride: kraken-grafana
  service:
    port: 80
  rbac:
    namespaced: true
  persistence:
    enabled: true
  ingress:
    # Use grafana/grafana-ingress.yaml instead (does not work with the one of the Grafana helm chart)
    enabled: false
  plugins:
    - grafana-piechart-panel
    - blackmirror1-singlestat-math-panel
  adminPassword: *default_admin_pwd
  grafana.ini:
    server:
      protocol: "http"
      domain: "localhost"
      root_url: "%(protocol)s://%(domain)s/grafana/"
# TODO reprendre les autres modifications qui sont faites sur grafana.ini

# Service name is .Release.Name-influxdb
influxdb:
  fullnameOverride: kraken-influxdb
  env:
    - name: INFLUXDB_ADMIN_USER
      value: admin
    - name: INFLUXDB_ADMIN_PASSWORD
      value: *default_admin_pwd
  config:
    http:
      bind_address: 8086